- pipeline_name: successfull_payments
  pipeline_type: stan
  transform:
    workers: 3
    buffer:
      size: 2000
      events: 40
  output:
    workers: 3
    buffer:
      size: 2000
      events: 40

- pipeline_name: failed_payments
  pipeline_type: stan
  transform:
    workers: 3
    buffer:
      size: 2000
      events: 40
  output:
    workers: 3
    buffer:
      size: 2000
      events: 40
