- pipeline_name: successfull_payments
  pipeline_type: stan
  transform:
    workers: 3
    buffer:
      size: 1234
      events: 12
  output:
    workers: 7
    buffer:
      size: 5678
      events: 34

- pipeline_name: failed_payments
  pipeline_type: stan
  transform:
    workers: 4
    buffer:
      size: 4321
      events: 14
  output:
    workers: 5
    buffer:
      size: 8765
      events: 88
